version: '3.7'

services:

  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

